version:  '3'
services:
  datascience-notebook:
      image:    jupyter/tensorflow-notebook
      volumes:
        - .:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   jupyter_notebook
